# Generated by Django 3.1.7 on 2021-02-26 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='', max_length=1)),
                ('status', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
