# Generated by Django 3.1.7 on 2021-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210226_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A+', 'A+'), ('B', 'B'), ('B+', 'B+'), ('AB', 'AB'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
    ]
