# Generated by Django 3.1.7 on 2021-02-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('infectious', 'infectious'), ('deficiency', 'deficiency'), ('hereditary', 'hereditary'), ('physiological', 'physiological')], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Types of Diseases',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symptom', models.TextField()),
                ('prevention', models.TextField()),
                ('treatment', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diseasetypes')),
            ],
            options={
                'verbose_name_plural': 'List of Diseases',
            },
        ),
    ]
