# Generated by Django 3.1.7 on 2021-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cause',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
