# Generated by Django 3.1.7 on 2021-02-26 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patient_blood_type'),
        ('main', '0002_disease_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('temprature_in_c', models.PositiveSmallIntegerField()),
                ('prescription', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient')),
            ],
            options={
                'verbose_name_plural': 'Current Medical Records',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
